//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrictSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilitaryDistrictSystemEntities : DbContext
    {
        private static MilitaryDistrictSystemEntities _context;
        public static MilitaryDistrictSystemEntities GetContext()
        {
            if (_context == null)
                _context = new MilitaryDistrictSystemEntities();

            return _context;

        }
        public MilitaryDistrictSystemEntities()
            : base("name=MilitaryDistrictSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вид_войск> Вид_войск { get; set; }
        public virtual DbSet<Личный_состав> Личный_состав { get; set; }
        public virtual DbSet<Места_дислокации> Места_дислокации { get; set; }
        public virtual DbSet<Роты> Роты { get; set; }
        public virtual DbSet<Части> Части { get; set; }
    }
}
