//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrictSystem
{
    using System;
    using System.Collections.Generic;

    public partial class Личный_состав
    {
        public int Код_состава { get; set; }
        public string Фамилия_ { get; set; }
        public string Имя_ { get; set; }
        public string Отчество_ { get; set; }
        public int Код_роты { get; set; }
        public string Должность_ { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Год_поступления_на_службу { get; set; }
        public int Выслуга_лет { get; set; }
        public string Награды_ { get; set; }
        public string Участие_в_военных_мероприятиях { get; set; }
        public string Фото { get; set; }
    
        public virtual Роты Роты { get; set; }
        public string RotaString { get { return Роты.Название_роты; } }
        public int NumChast { get { return Роты.Номер_части; } }
        
    }
}
