//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrictSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Места_дислокации
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Места_дислокации()
        {
            this.Части = new HashSet<Части>();
        }
    
        public int Код_дислокации { get; set; }
        public string Страна_ { get; set; }
        public string Город_ { get; set; }
        public string Адрес_ { get; set; }
        public decimal Занимаемая_площадь { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Части> Части { get; set; }
    }
}
