//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrictSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Роты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Роты()
        {
            this.Личный_состав = new HashSet<Личный_состав>();
        }
    
        public int Код_роты { get; set; }
        public string Название_роты { get; set; }
        public int Количество_служащих { get; set; }
        public int Номер_части { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Личный_состав> Личный_состав { get; set; }
        public virtual Части Части { get; set; }
    }
}
