//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrictSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Части
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Части()
        {
            this.Роты = new HashSet<Роты>();
        }
    
        public int Номер_части { get; set; }
        public string Название_части { get; set; }
        public int Код_дислокации { get; set; }
        public int Код_войска { get; set; }
        public int Количество_рот { get; set; }
    
        public virtual Вид_войск Вид_войск { get; set; }
        public virtual Места_дислокации Места_дислокации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Роты> Роты { get; set; }
    }
}
